### PR TITLE
fix: update keygen, crypto, go-jose, go-jwt-middleware

### LINKED ISSUE #252: square/go-jose deprecated
- https://github.com/square/go-jose has been replaced with
- https://github.com/go-jose/go-jose
- only a couple minor updates since then in v2 2.6.0->2.6.2
- but also there is a v3 in that repo

i didnt update it myself because it updated my crypto or something causing:

```
# github.com/caarlos0/sshmarshal
..\go\pkg\mod\github.com\caarlos0\sshmarshal@v0.1.0\marshal.go:29:6: MarshalPrivateKey already declared through dot-import of package ssh ("golang.org/x/crypto/ssh")
        ..\go\pkg\mod/golang.org/x/crypto@v0.18.0/ssh/keys.go:302:6: other declaration of MarshalPrivateKey
..\go\pkg\mod\github.com\caarlos0\sshmarshal@v0.1.0\marshal.go:35:6: MarshalPrivateKeyWithPassphrase already declared through dot-import of package ssh ("golang.org/x/crypto/ssh")
        ..\go\pkg\mod/golang.org/x/crypto@v0.18.0/ssh/keys.go:308:6: other declaration of MarshalPrivateKeyWithPassphrase
```
which i think is a separate but related issue i've hit at least one other time.

### LINKED ISSUE #253: auth0/go-jwt-middleware/v2@v2.0.1 cannot be upgraded
cannot upgrade go-jwt-middleware due to crypto v0.17 being used
```
go get github.com/auth0/go-jwt-middleware/v2@v2.0.1
go: downgraded github.com/auth0/go-jwt-middleware/v2 v2.2.1 => v2.0.1
```
even if it compiles, it seems to mark all charm jwt as invalid

### LINKED ISSUE #254: crypto cannot be upgraded due to dot-import from caarlos0/sshmarshal
```
# github.com/caarlos0/sshmarshal
..\go\pkg\mod\github.com\caarlos0\sshmarshal@v0.1.0\marshal.go:29:6: MarshalPrivateKey already declared through dot-import of package ssh ("golang.org/x/crypto/ssh")
        ..\go\pkg\mod/golang.org/x/crypto@v0.18.0/ssh/keys.go:302:6: other declaration of MarshalPrivateKey
..\go\pkg\mod\github.com\caarlos0\sshmarshal@v0.1.0\marshal.go:35:6: MarshalPrivateKeyWithPassphrase already declared through dot-import of package ssh ("golang.org/x/crypto/ssh")
        ..\go\pkg\mod/golang.org/x/crypto@v0.18.0/ssh/keys.go:308:6: other declaration of MarshalPrivateKeyWithPassphrase
```
various issues are related to this, maybe a new release of caarlos0/sshmarshal which doesn't have those dot-imported?

### PR DESCRIPTION
**Pull request by caarlos0**
closes #254 
closes #253
closes #252

### CODE REVIEW

**Review by aymanbagabas — APPROVED** [review]

**Comment by dezren39** [comment]
thank you for looking into this, i appreciate it very much

File: server/http.go [hunk 1]
```diff
@@ -97,15 +97,15 @@ func NewHTTPServer(cfg *Config) (*HTTPServer, error) {
...
 	mux.HandleFunc(pat.Post("/v1/fs/*"), s.handlePostFile)
 	mux.HandleFunc(pat.Delete("/v1/fs/*"), s.handleDeleteFile)
 	mux.HandleFunc(pat.Get("/v1/seq/:name"), s.handleGetSeq)
 	mux.HandleFunc(pat.Post("/v1/seq/:name"), s.handlePostSeq)
-	mux.HandleFunc(pat.Get("/v1/news"), s.handleGetNewsList)
+	mux.HandleFunc(pat.Get("/ v1 / news"), s.handleGetNewsList)
 	mux.HandleFunc(pat.Get("/v1/news/:id"), s.handleGetNews)
-	mux.HandleFunc(pat.Get("/v1/public/jwks"), s.handleJWKS)
-	mux.HandleFunc(pat.Get("/.well-known/openid-configuration"), s.handleOpenIDConfig)
+	mux.HandleFunc(pat.Get("/ v1 / public / jwks"), s.handleJWKS)
```
Comment (dezren39) [inline server/http.go:107]: what do these spaces do?

File: go.mod [hunk 2]
```diff
@@ -3,17 +3,18 @@ module github.com/charmbracelet/charm
...
 	github.com/charmbracelet/bubbles v0.15.0
 	github.com/charmbracelet/bubbletea v0.23.2
-	github.com/charmbracelet/keygen v0.4.2
+	github.com/charmbracelet/keygen v0.5.0
 	github.com/charmbracelet/lipgloss v0.7.1
 	github.com/charmbracelet/log v0.2.2
 	github.com/charmbracelet/ssh v0.0.0-20221117183211-483d43d97103
 	github.com/charmbracelet/wish v1.1.1
 	github.com/dgraph-io/badger/v3 v3.2103.2
+	github.com/go-jose/go-jose v2.6.2+incompatible
```
Comment (dezren39) [inline go.mod:17]: neat, i didn't know about +incompatible
resources
- https://utcc.utoronto.ca/~cks/space/blog/programming/GoModulePlusIncompatibleMeaning
- https://stackoverflow.com/questions/57355929/what-does-incompatible-in-go-mod-mean-will-it-cause-harm

**Review by aymanbagabas — APPROVED** [review]
